### ISSUE TITLE
Incorrect isolator pinout

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-owo#27]
![image](https://user-images.githubusercontent.com/1595938/198888418-b16910e7-c4d9-46d1-8dd4-e2cae258eda6.png)

Right side pin numbers are in reverse order.

Correct pinout:
![image](https://user-images.githubusercontent.com/1595938/198888339-7d1a3ed1-67f7-41a6-8878-b1ddb2962729.png)

**Comment by dakoko** [comment]
Fixed the isolator pinout and rerouted things accordingly

**Comment by ReikoR** [comment]
Some pins are still incorrect:
![image](https://user-images.githubusercontent.com/1595938/200173924-ccde43ec-59a9-44f7-b45f-4ca6f1304a01.png)

**Comment by dakoko** [comment]
Fixed the power pin order.
